// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEEnMijmh4oMd7k7TjdpfBwMMwNk4AGBs',
    appId: '1:132680359432:web:20c27aefb79d88777a3bbd',
    messagingSenderId: '132680359432',
    projectId: 'banki-app-eg',
    authDomain: 'banki-app-eg.firebaseapp.com',
    storageBucket: 'banki-app-eg.appspot.com',
    measurementId: 'G-DD1T42H587',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8Zh7k2wGMgK6HKDMKfT9NBqh_HByo0LY',
    appId: '1:132680359432:android:40e51ea486dced187a3bbd',
    messagingSenderId: '132680359432',
    projectId: 'banki-app-eg',
    storageBucket: 'banki-app-eg.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4FPR_SpG7qSzNH6NmtT4LIO6z5lhmKbM',
    appId: '1:132680359432:ios:69ed1170c40246607a3bbd',
    messagingSenderId: '132680359432',
    projectId: 'banki-app-eg',
    storageBucket: 'banki-app-eg.appspot.com',
    iosBundleId: 'com.example.bankiApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4FPR_SpG7qSzNH6NmtT4LIO6z5lhmKbM',
    appId: '1:132680359432:ios:69ed1170c40246607a3bbd',
    messagingSenderId: '132680359432',
    projectId: 'banki-app-eg',
    storageBucket: 'banki-app-eg.appspot.com',
    iosBundleId: 'com.example.bankiApp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEEnMijmh4oMd7k7TjdpfBwMMwNk4AGBs',
    appId: '1:132680359432:web:39030d03eb5c30587a3bbd',
    messagingSenderId: '132680359432',
    projectId: 'banki-app-eg',
    authDomain: 'banki-app-eg.firebaseapp.com',
    storageBucket: 'banki-app-eg.appspot.com',
    measurementId: 'G-E71FRHS5W3',
  );
}
